IF  NOT EXISTS(SELECT * FROM sys.columns 
	WHERE Name = N'uuid' AND OBJECT_ID = OBJECT_ID(N'DT_TBL_VIATICO_COMPROBACION_GASTOS'))
BEGIN
	ALTER TABLE DT_TBL_VIATICO_COMPROBACION_GASTOS add uuid varchar(50)
END
