--TABLAS A MODIFICAR EN DECIMAL
USE IICA_1
GO

ALTER TABLE DT_TBL_VACACIONES
ALTER COLUMN Total_Dias_Saldo_Vacacional DECIMAL(4,2)
GO

ALTER TABLE DT_CAT_DIAS_VACACIONES
ALTER COLUMN Dias_Vacaciones DECIMAL(4,2)
GO

ALTER TABLE DT_TBL_PERIODO_VACACIONAL_EMPLEADO
ALTER COLUMN Saldo_Periodo_Anterior DECIMAL(4,2)
GO
ALTER TABLE DT_TBL_PERIODO_VACACIONAL_EMPLEADO
ALTER COLUMN Saldo_Periodo_Anterior_Usado DECIMAL(4,2)
GO
ALTER TABLE DT_TBL_PERIODO_VACACIONAL_EMPLEADO
ALTER COLUMN Saldo_Proporcional_Actual DECIMAL(4,2)
GO
ALTER TABLE DT_TBL_PERIODO_VACACIONAL_EMPLEADO
ALTER COLUMN Saldo_Proporcional_Actual_Usado DECIMAL(4,2)
GO
ALTER TABLE DT_TBL_PERIODO_VACACIONAL_EMPLEADO
ALTER COLUMN Saldo_Actual_Disponible DECIMAL(4,2)
GO
ALTER TABLE DT_TBL_PERIODO_VACACIONAL_EMPLEADO
ALTER COLUMN Saldo_Actual_Utilizado DECIMAL(4,2)
GO
ALTER TABLE DT_TBL_PERIODO_VACACIONAL_EMPLEADO
ALTER COLUMN Saldo_Correspondiente DECIMAL(4,2)
GO
